"agentImagePullSecret": "eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZW52MC1ncHItcHVibGljLXJlYWRlciIsInBhc3N3b3JkIjoiZ2hwX0U4WWJ3Zk15bkFUMFVobERybUtyRUxqc0w5a0JUMzIxUmFnMyIsImVtYWlsIjoic3VwcG9ydEBlbnYwLmNvbSIsImF1dGgiOiJaVzUyTUMxbmNISXRjSFZpYkdsakxYSmxZV1JsY2pwbmFIQmZSVGhaWW5kbVRYbHVRVlF3Vldoc1JISnRTM0pGVEdwelREbHJRbFF6TWpGU1lXY3oifX19Cg=="
"agentKey": "acme-fitness"
"agentProxy":
  "install": true
"apiGatewayUrl": "https://acme-fitness.agent.api.env0.com/acme-fitness"
"awsAccessKeyIdEncoded": "QUtJQTVKR1ZVQzVKUkZCTVlYV1g="
"awsSecretAccessKeyEncoded": "eGpINFBiY09PNVRtL3NFZmxGbnRDREtGRTc3dFJEek9TanVXVlBTcg=="
"awsSecretsRegion": "us-east-1"
"deploymentResultSqsUrl": "https://sqs.us-east-1.amazonaws.com/913128560467/shared-prod-deployment-completed-queue"
"deploymentTriggerApi": "https://9ityynreib.execute-api.us-east-1.amazonaws.com/acme-fitness/deployment-tasks/pending"
"deploymentTriggerSqsUrl": "https://sqs.us-east-1.amazonaws.com/913128560467/acme-fitness-deployment-trigger-queue"
"env0ApiGwKeyEncoded": "cU1FSXFqVmhPMTkxSlppMHRwSHZJOGhYQjR1YkoxWXkyeGxxWnhMTQ=="
"eventsTopicArn": "arn:aws:sns:us-east-1:913128560467:shared-prod-events"
"httpProxyRequestSqsUrl": "https://sqs.us-east-1.amazonaws.com/913128560467/acme-fitness-http-proxy-request-queue"
"httpProxyResponseBucketName": "shared-prod-http-proxy-response"
"isSelfHosted": "true"
"limits":
  "cpu": "460m"
  "memory": "1500Mi"
"outputLogsLogGroupName": "prerequisites-prod-k8s-shag-logs"
"prerequisitesStackName": "prerequisites-prod"
"region": "us-east-1"
"sharedStackPrefix": "shared-prod-"
"stage": "prod"
"stateMountPath": "/mnt/private/env0"
